/**
 * Generate TypeScript types from the OpenAPI schema.
 *
 * Uses openapi-typescript (v7) to produce accurate types that handle
 * allOf, oneOf, anyOf, nested objects, enums, and $ref resolution.
 *
 * Usage:
 *   1. Run `python scripts/export_openapi.py` to produce web/openapi.json
 *   2. Run `pnpm types:generate` to produce web/src/types/generated/api.ts
 *
 * The generated file is checked into source control. The drift-check
 * script verifies it stays in sync.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import openapiTS from 'openapi-typescript'

const OPENAPI_JSON = resolve(import.meta.dirname, '..', 'openapi.json')
const OUTPUT_FILE = resolve(import.meta.dirname, '..', 'src', 'types', 'generated', 'api.ts')

async function main(): Promise<void> {
  // Ensure the OpenAPI schema exists
  if (!existsSync(OPENAPI_JSON)) {
    console.error('OpenAPI schema not found. Run: python scripts/export_openapi.py')
    process.exit(1)
  }

  // Generate types using openapi-typescript
  const schemaPath = new URL(`file://${OPENAPI_JSON.replace(/\\/g, '/')}`)
  const generated = await openapiTS(schemaPath)

  // Read schema for metadata (endpoints, version)
  const schema = JSON.parse(readFileSync(OPENAPI_JSON, 'utf-8')) as {
    paths: Record<string, Record<string, unknown>>
    info?: { version?: string }
  }

  // Build the output file
  const lines: string[] = [
    '/* eslint-disable */',
    '// This file is auto-generated by scripts/generate-types.ts',
    '// Do not edit manually. Run `pnpm types:generate` to regenerate.',
    '',
    generated,
    '',
  ]

  // Record the endpoint paths for drift detection
  lines.push('// ── Known endpoints ───────────────────────────────────────────')
  lines.push('')
  lines.push('export const KNOWN_ENDPOINTS = [')
  for (const path of Object.keys(schema.paths)) {
    lines.push(`  '${path}',`)
  }
  lines.push('] as const')
  lines.push('')

  // Record the schema version from the spec
  if (schema.info?.version) {
    lines.push(`export const API_VERSION = '${schema.info.version}'`)
  }

  // Ensure output directory exists
  mkdirSync(dirname(OUTPUT_FILE), { recursive: true })
  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')
  console.log(`Generated types written to ${OUTPUT_FILE}`)
  console.log(`  Endpoints: ${Object.keys(schema.paths).length}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
