/**
 * Generate TypeScript types from the OpenAPI schema.
 *
 * Usage:
 *   1. Run `python scripts/export_openapi.py` to produce web/openapi.json
 *   2. Run `pnpm types:generate` to produce web/src/types/generated/api.ts
 *
 * The generated file is checked into source control. The drift-check
 * script verifies it stays in sync.
 */

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

const OPENAPI_JSON = resolve(import.meta.dirname, '..', 'openapi.json')
const OUTPUT_FILE = resolve(import.meta.dirname, '..', 'src', 'types', 'generated', 'api.ts')

async function main(): Promise<void> {
  // Ensure the OpenAPI schema exists
  if (!existsSync(OPENAPI_JSON)) {
    console.error('OpenAPI schema not found. Run: python scripts/export_openapi.py')
    process.exit(1)
  }

  // Read and parse the schema to extract a summary
  const schema = JSON.parse(readFileSync(OPENAPI_JSON, 'utf-8')) as {
    paths: Record<string, Record<string, unknown>>
    components?: { schemas?: Record<string, unknown> }
  }

  // Generate types manually from the schema structure
  // (openapi-typescript has ESM compatibility issues in some environments,
  //  so we do a lightweight extraction here)
  const lines: string[] = [
    '/* eslint-disable */',
    '// This file is auto-generated by scripts/generate-types.ts',
    '// Do not edit manually. Run `pnpm types:generate` to regenerate.',
    '',
  ]

  // Extract schema names
  const schemas = schema.components?.schemas ?? {}
  const schemaNames = Object.keys(schemas)

  if (schemaNames.length > 0) {
    lines.push('// ── Schema-derived interfaces ──────────────────────────────────')
    lines.push('')

    for (const name of schemaNames) {
      const schemaObj = schemas[name] as Record<string, unknown>
      lines.push(`export interface ${name} {`)

      const properties = (schemaObj.properties ?? {}) as Record<string, Record<string, unknown>>
      const required = (schemaObj.required ?? []) as string[]

      for (const [propName, propSchema] of Object.entries(properties)) {
        const isRequired = required.includes(propName)
        const tsType = openApiTypeToTs(propSchema)
        const optionalMark = isRequired ? '' : '?'
        lines.push(`  ${toCamel(propName)}${optionalMark}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')
    }
  }

  // Record the endpoint paths for drift detection
  lines.push('// ── Known endpoints ───────────────────────────────────────────')
  lines.push('')
  lines.push('export const KNOWN_ENDPOINTS = [')
  for (const path of Object.keys(schema.paths)) {
    lines.push(`  '${path}',`)
  }
  lines.push('] as const')
  lines.push('')

  // Record the schema version from the spec
  const info = (schema as Record<string, unknown>).info as Record<string, unknown> | undefined
  if (info?.version) {
    lines.push(`export const API_VERSION = '${info.version}'`)
  }

  // Ensure output directory exists
  mkdirSync(dirname(OUTPUT_FILE), { recursive: true })
  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')
  console.log(`Generated types written to ${OUTPUT_FILE}`)
  console.log(`  Schemas: ${schemaNames.length}`)
  console.log(`  Endpoints: ${Object.keys(schema.paths).length}`)
}

/** Map OpenAPI type to TypeScript type. */
function openApiTypeToTs(schema: Record<string, unknown>): string {
  if (schema.$ref) {
    const ref = schema.$ref as string
    const name = ref.split('/').pop() ?? 'unknown'
    return name
  }

  const type = schema.type as string
  switch (type) {
    case 'string':
      return 'string'
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array': {
      const items = schema.items as Record<string, unknown> | undefined
      if (!items) return 'unknown[]'
      return `${openApiTypeToTs(items)}[]`
    }
    case 'object': {
      const additional = schema.additionalProperties as Record<string, unknown> | undefined
      if (additional) {
        return `Record<string, ${openApiTypeToTs(additional)}>`
      }
      return 'Record<string, unknown>'
    }
    default:
      return 'unknown'
  }
}

/** Convert snake_case to camelCase. */
function toCamel(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
