"""`sclpl docs build` — generate `docs/reference/` from what is registered.

Invariant 10: **`docs/reference/` is generated, and hand-editing it fails CI.** The
reason is not tidiness. A reference written by hand describes what someone believed was
true when they wrote it; one generated from the registry describes what is true now. The
second kind cannot drift, and the first kind always does.

CI runs this and diffs the result. A non-empty diff fails the build, which is the same
mechanism as `ruff format --check`: the fix is to run the command, and the failure tells
you so.
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from sclpl.errors import EXIT_VALIDATION

REFERENCE = Path("docs/reference")

HEADER = """<!-- Generated by `sclpl docs build`. Do not edit.
     Invariant 10: a hand-written reference describes what someone believed when they
     wrote it; a generated one describes what is true now. -->

"""


def register(root: typer.Typer) -> None:
    app = typer.Typer(no_args_is_help=True, help="Generate the reference documentation.")
    app.command("build")(build)
    root.add_typer(app, name="docs")


def build(
    into: Annotated[Path, typer.Option("--into", help="Where to write.")] = REFERENCE,
    check: Annotated[
        bool,
        typer.Option("--check", help="Fail if what is on disk is out of date. For CI."),
    ] = False,
) -> None:
    """Write the reference, or check it is current."""
    from sclpl import bootstrap

    bootstrap.load()

    pages = {
        "functions.md": _functions(),
        "expressions.md": _expressions(),
        "cli.md": _cli(),
        "plugins.md": _plugins(),
    }

    if check:
        stale = [
            name
            for name, body in pages.items()
            if not (into / name).is_file() or (into / name).read_text(encoding="utf-8") != body
        ]
        if stale:
            typer.echo(f"out of date: {', '.join(stale)}", err=True)
            typer.echo("run 'sclpl docs build' and commit the result", err=True)
            raise typer.Exit(EXIT_VALIDATION)
        typer.echo(f"{len(pages)} pages up to date", err=True)
        return

    into.mkdir(parents=True, exist_ok=True)
    for name, body in pages.items():
        (into / name).write_text(body, encoding="utf-8")
    typer.echo(f"wrote {len(pages)} pages to {into}", err=True)


def _functions() -> str:
    """Every registered function, grouped by whether it is built in."""
    from sclpl.ext.functions import REGISTRY

    lines = [HEADER, "# Functions\n"]
    builtin = sorted(name for name, entry in REGISTRY.items() if entry.builtin)
    contributed = sorted(name for name, entry in REGISTRY.items() if not entry.builtin)

    for title, names in (("Built in", builtin), ("From plugins", contributed)):
        if not names:
            continue
        lines.append(f"\n## {title}\n")
        lines.append("| Function | Summary |")
        lines.append("|---|---|")
        for name in names:
            entry = REGISTRY[name]
            lines.append(f"| `{entry.signature()}` | {entry.summary} |")
    return "\n".join(lines) + "\n"


def _expressions() -> str:
    """Every operator in the dispatch table, and the types it accepts."""
    from sclpl.expr import dispatch

    lines = [HEADER, "# Expressions\n"]
    lines.append("One dispatch table, keyed by name and the runtime type of the first")
    lines.append("argument. `any` means the operator does not care.\n")
    lines.append("| Operator | Accepts | Summary |")
    lines.append("|---|---|---|")
    for name in dispatch.names():
        types = ", ".join(dispatch.types_for(name)) or "any"
        lines.append(f"| `{name}` | {types} | {dispatch.SUMMARY.get(name, '')} |")
    return "\n".join(lines) + "\n"


def _cli() -> str:
    """Every command and its help, read off the Typer app rather than transcribed."""
    from sclpl.cli.app import app

    lines = [HEADER, "# Commands\n", "| Command | What it does |", "|---|---|"]
    for command in app.registered_commands:
        name = command.name or (command.callback.__name__ if command.callback else "")
        help_text = (command.help or _first_line(command.callback)).strip()
        lines.append(f"| `sclpl {name}` | {help_text} |")
    for group in app.registered_groups:
        lines.append(f"| `sclpl {group.name}` | {(group.help or '').strip()} |")
    return "\n".join(lines) + "\n"


def _plugins() -> str:
    """What is installed, and what each contributes."""
    from sclpl.ext import plugins as ext

    registry = ext.discover()
    lines = [HEADER, "# Plugins\n", "| Plugin | Version | Capabilities | Contributes |"]
    lines.append("|---|---|---|---|")
    for plugin in sorted(registry.plugins.values(), key=lambda item: item.name):
        caps = ", ".join(sorted(plugin.capabilities)) or "none"
        gives = ", ".join(f"`{item.name}`" for item in plugin.contributes) or "-"
        lines.append(f"| {plugin.name} | {plugin.version} | {caps} | {gives} |")
    return "\n".join(lines) + "\n"


def _first_line(callback: object) -> str:
    doc = getattr(callback, "__doc__", "") or ""
    return doc.strip().splitlines()[0] if doc.strip() else ""
