"""
@name: html_report
@type: report
@version: 1
@description: Generate HTML reports from workflow data

Config via workflow_variables: report_title, report_data_source,
report_template (simple/table/list), report_output_path.
"""

import json
import html


def _render_table(data: list[dict], title: str) -> str:
    if not data:
        return f"<h2>{html.escape(title)}</h2><p>No data available.</p>"

    headers = []
    for item in data:
        if isinstance(item, dict):
            for key in item:
                if key not in headers:
                    headers.append(key)

    rows = []
    for item in data:
        if isinstance(item, dict):
            cells = "".join(f"<td>{html.escape(str(item.get(h, '')))}</td>" for h in headers)
            rows.append(f"<tr>{cells}</tr>")

    ths = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    return f"""
    <h2>{html.escape(title)}</h2>
    <table>
        <thead><tr>{ths}</tr></thead>
        <tbody>{''.join(rows)}</tbody>
    </table>
    """


def _render_list(data: list | dict, title: str) -> str:
    items = data if isinstance(data, list) else [data]
    lis = "".join(f"<li>{html.escape(str(item))}</li>" for item in items)
    return f"<h2>{html.escape(title)}</h2><ul>{lis}</ul>"


def run(ctx):
    title = ctx.workflow_variables.get("report_title", "SCLPLAPI Report")
    source_key = ctx.workflow_variables.get("report_data_source", "")
    template = ctx.workflow_variables.get("report_template", "table")
    output_path = ctx.workflow_variables.get("report_output_path", "")

    data = ctx.workflow_variables.get(source_key) if source_key else None
    if data is None:
        data = ctx.step_outputs.get(source_key, []) if source_key else []

    if isinstance(data, str):
        try:
            data = json.loads(data)
        except (json.JSONDecodeError, TypeError):
            data = [{"value": data}]

    body_content = ""
    if template == "table" and isinstance(data, list):
        body_content = _render_table(data, title)
    elif template == "list":
        body_content = _render_list(data, title)
    else:
        body_content = f"<h2>{html.escape(title)}</h2><pre>{html.escape(json.dumps(data, indent=2))}</pre>"

    report = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; }}
        h1 {{ color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 0.5rem; }}
        h2 {{ color: #16213e; margin-top: 1.5rem; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
        th {{ background-color: #16213e; color: white; }}
        tr:nth-child(even) {{ background-color: #f8f9fa; }}
        pre {{ background: #f4f4f4; padding: 1rem; border-radius: 4px; overflow-x: auto; }}
        .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 1rem; }}
    </style>
</head>
<body>
    <h1>{html.escape(title)}</h1>
    <p class="meta">Generated by SCLPLAPI</p>
    {body_content}
</body>
</html>"""

    ctx.workflow_variables["html_report"] = report

    if output_path:
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(report)
        except OSError as exc:
            return {"success": False, "error": f"Failed to write report: {exc}"}

    return {
        "success": True,
        "report_length": len(report),
        "output_path": output_path or "(in memory)",
    }
