"""
@name: markdown_report
@type: report
@version: 1
@description: Generate Markdown reports from workflow data

Config via workflow_variables: report_title, report_data_source,
report_template (table/list/json), report_output_path.
"""

import json


def _md_table(data: list[dict]) -> str:
    if not data:
        return "*No data available.*\n"

    headers = []
    for item in data:
        if isinstance(item, dict):
            for key in item:
                if key not in headers:
                    headers.append(key)

    header_row = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"

    rows = []
    for item in data:
        if isinstance(item, dict):
            cells = " | ".join(str(item.get(h, "")) for h in headers)
            rows.append(f"| {cells} |")

    return "\n".join([header_row, separator] + rows) + "\n"


def _md_list(data: list | dict) -> str:
    items = data if isinstance(data, list) else [data]
    return "\n".join(f"- {item}" for item in items) + "\n"


def run(ctx):
    title = ctx.workflow_variables.get("report_title", "SCLPLAPI Report")
    source_key = ctx.workflow_variables.get("report_data_source", "")
    template = ctx.workflow_variables.get("report_template", "table")
    output_path = ctx.workflow_variables.get("report_output_path", "")

    data = ctx.workflow_variables.get(source_key) if source_key else None
    if data is None:
        data = ctx.step_outputs.get(source_key, []) if source_key else []

    if isinstance(data, str):
        try:
            data = json.loads(data)
        except (json.JSONDecodeError, TypeError):
            data = [{"value": data}]

    sections = [f"# {title}\n"]
    sections.append("*Generated by SCLPLAPI*\n")

    if template == "table" and isinstance(data, list) and data and isinstance(data[0], dict):
        sections.append(_md_table(data))
    elif template == "list":
        sections.append(_md_list(data))
    else:
        sections.append(f"```json\n{json.dumps(data, indent=2)}\n```\n")

    report = "\n".join(sections)
    ctx.workflow_variables["markdown_report"] = report

    if output_path:
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(report)
        except OSError as exc:
            return {"success": False, "error": f"Failed to write report: {exc}"}

    return {
        "success": True,
        "report_length": len(report),
        "output_path": output_path or "(in memory)",
    }
